// Generated by tools/generate.py from spec/api_inventory.json — do not edit.
#pragma once

/// @file
/// @brief Generated collect_files overloads for InputFile-bearing types.

#include <vector>

#include "tgbot/detail/collect.hpp"
#include "tgbot/types.hpp"

namespace tgbot {

void collect_files(const InputPollOption& value, std::vector<MultipartPart>& out);
void collect_files(const InputMediaAnimation& value, std::vector<MultipartPart>& out);
void collect_files(const InputMediaAudio& value, std::vector<MultipartPart>& out);
void collect_files(const InputMediaDocument& value, std::vector<MultipartPart>& out);
void collect_files(const InputMediaLivePhoto& value, std::vector<MultipartPart>& out);
void collect_files(const InputMediaPhoto& value, std::vector<MultipartPart>& out);
void collect_files(const InputMediaSticker& value, std::vector<MultipartPart>& out);
void collect_files(const InputMediaVideo& value, std::vector<MultipartPart>& out);
void collect_files(const InputMediaVoiceNote& value, std::vector<MultipartPart>& out);
void collect_files(const InputPaidMediaLivePhoto& value, std::vector<MultipartPart>& out);
void collect_files(const InputPaidMediaPhoto& value, std::vector<MultipartPart>& out);
void collect_files(const InputPaidMediaVideo& value, std::vector<MultipartPart>& out);
void collect_files(const InputProfilePhotoStatic& value, std::vector<MultipartPart>& out);
void collect_files(const InputProfilePhotoAnimated& value, std::vector<MultipartPart>& out);
void collect_files(const InputStoryContentPhoto& value, std::vector<MultipartPart>& out);
void collect_files(const InputStoryContentVideo& value, std::vector<MultipartPart>& out);
void collect_files(const InputSticker& value, std::vector<MultipartPart>& out);
void collect_files(const InputRichMessage& value, std::vector<MultipartPart>& out);
void collect_files(const InputRichMessageMedia& value, std::vector<MultipartPart>& out);
void collect_files(const InputRichBlockListItem& value, std::vector<MultipartPart>& out);
void collect_files(const InputRichBlockList& value, std::vector<MultipartPart>& out);
void collect_files(const InputRichBlockBlockQuotation& value, std::vector<MultipartPart>& out);
void collect_files(const InputRichBlockCollage& value, std::vector<MultipartPart>& out);
void collect_files(const InputRichBlockSlideshow& value, std::vector<MultipartPart>& out);
void collect_files(const InputRichBlockDetails& value, std::vector<MultipartPart>& out);
void collect_files(const InputRichBlockAnimation& value, std::vector<MultipartPart>& out);
void collect_files(const InputRichBlockAudio& value, std::vector<MultipartPart>& out);
void collect_files(const InputRichBlockPhoto& value, std::vector<MultipartPart>& out);
void collect_files(const InputRichBlockVideo& value, std::vector<MultipartPart>& out);
void collect_files(const InputRichBlockVoiceNote& value, std::vector<MultipartPart>& out);
void collect_files(const InlineQueryResultArticle& value, std::vector<MultipartPart>& out);
void collect_files(const InlineQueryResultPhoto& value, std::vector<MultipartPart>& out);
void collect_files(const InlineQueryResultGif& value, std::vector<MultipartPart>& out);
void collect_files(const InlineQueryResultMpeg4Gif& value, std::vector<MultipartPart>& out);
void collect_files(const InlineQueryResultVideo& value, std::vector<MultipartPart>& out);
void collect_files(const InlineQueryResultAudio& value, std::vector<MultipartPart>& out);
void collect_files(const InlineQueryResultVoice& value, std::vector<MultipartPart>& out);
void collect_files(const InlineQueryResultDocument& value, std::vector<MultipartPart>& out);
void collect_files(const InlineQueryResultLocation& value, std::vector<MultipartPart>& out);
void collect_files(const InlineQueryResultVenue& value, std::vector<MultipartPart>& out);
void collect_files(const InlineQueryResultContact& value, std::vector<MultipartPart>& out);
void collect_files(const InlineQueryResultCachedPhoto& value, std::vector<MultipartPart>& out);
void collect_files(const InlineQueryResultCachedGif& value, std::vector<MultipartPart>& out);
void collect_files(const InlineQueryResultCachedMpeg4Gif& value, std::vector<MultipartPart>& out);
void collect_files(const InlineQueryResultCachedSticker& value, std::vector<MultipartPart>& out);
void collect_files(const InlineQueryResultCachedDocument& value, std::vector<MultipartPart>& out);
void collect_files(const InlineQueryResultCachedVideo& value, std::vector<MultipartPart>& out);
void collect_files(const InlineQueryResultCachedVoice& value, std::vector<MultipartPart>& out);
void collect_files(const InlineQueryResultCachedAudio& value, std::vector<MultipartPart>& out);
void collect_files(const InputRichMessageContent& value, std::vector<MultipartPart>& out);

}  // namespace tgbot
