// Generated by tools/generate.py from spec/api_inventory.json — do not edit.
#pragma once

#include <string_view>

namespace tgbot {

/// The Telegram Bot API version this library implements.
/// @see https://core.telegram.org/bots/api-changelog
constexpr std::string_view api_version() noexcept {
    return "10.2";
}

/// The version of the tgbot library itself.
constexpr std::string_view library_version() noexcept {
    return "0.1.0";
}

}  // namespace tgbot
