#!/usr/bin/env python3
"""Generate the C++ type system, JSON glue, registry and round-trip tests from
spec/api_inventory.json.

Emits (all files carry a do-not-edit banner):
  include/tgbot/types.hpp        every API object type
  include/tgbot/version.hpp      api_version()
  src/generated/types_json_*.cpp to_json/from_json definitions (sharded)
  src/generated/registry.cpp     implemented-symbol registry (coverage gate)
  tests/unit/generated/roundtrip_corpus_*.cpp  synthetic round-trip samples

Run from anywhere: paths are anchored to the repo root.
"""

from __future__ import annotations

import json
import re
import textwrap
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INV = ROOT / "spec" / "api_inventory.json"

BANNER = "// Generated by tools/generate.py from spec/api_inventory.json — do not edit.\n"

SCALAR_CPP = {
    "integer": "std::int64_t",
    "string": "std::string",
    "boolean": "bool",
    "true": "bool",
    "float": "double",
}

# Unions that cannot be dispatched by a discriminator literal.
STRUCTURAL_UNIONS = {"MaybeInaccessibleMessage", "InputMessageContent"}

# InputMessageContent subtypes in dispatch order (Venue before Location: both
# carry latitude, only Venue has title).
INPUT_MESSAGE_CONTENT_ORDER = [
    ("InputTextMessageContent", "message_text"),
    ("InputRichMessageContent", "rich_message"),
    ("InputContactMessageContent", "phone_number"),
    ("InputInvoiceMessageContent", "payload"),
    ("InputVenueMessageContent", "title"),
    ("InputLocationMessageContent", "latitude"),
]

# Ad-hoc aliases for inline unions that appear in the reference without a name.
REPLY_MARKUP_SET = frozenset(
    ["InlineKeyboardMarkup", "ReplyKeyboardMarkup", "ReplyKeyboardRemove", "ForceReply"]
)
NAMED_ADHOC_UNIONS = {
    # InputRichMessageMedia.media: not a subset of InputMedia (VoiceNote is
    # rich-message-only), so it gets its own alias.
    frozenset(
        [
            "InputMediaAnimation",
            "InputMediaAudio",
            "InputMediaPhoto",
            "InputMediaVideo",
            "InputMediaVoiceNote",
        ]
    ): "InputRichMessageMediaContent",
}

# Synthetic sample value overrides (field-exact), used by the round-trip corpus.
SAMPLE_OVERRIDES = {
    ("InaccessibleMessage", "date"): 0,  # docs: always 0, and the union dispatch key
}

NUM_JSON_SHARDS = 6
NUM_TEST_SHARDS = 4


def esc_doc(text: str) -> str:
    """Escape scraped description text for safe Doxygen output."""
    text = text.replace("\\", "&#92;")
    text = text.replace("@", "\\@")
    text = text.replace("<", "\\<").replace(">", "\\>")
    text = text.replace("&", "\\&")
    text = text.replace("#", "\\#")
    return text


def wrap_comment(text: str, indent: str) -> str:
    lines: list[str] = []
    for para in text.split("\n"):
        wrapped = textwrap.wrap(para, width=96 - len(indent)) or [""]
        lines.extend(wrapped)
    body = "\n".join(f"{indent}/// {line}".rstrip() for line in lines)
    if any(ord(c) > 127 for c in text):
        # clang-format miscounts display width of emoji and never settles on
        # these lines; guard them so format checks stay stable.
        body = f"{indent}// clang-format off\n{body}\n{indent}// clang-format on"
    return body


def paraphrase(desc: str) -> str:
    """Mechanical paraphrase of scraped descriptions for doc comments."""
    subs = [
        (r"^This object represents ", "Represents "),
        (r"^This object describes ", "Describes "),
        (r"^This object contains ", "Contains "),
        (r"^This object defines ", "Defines "),
        (r"^Describes that ", "Indicates that "),
        (r"^Use this method to ", "Uses the Bot API to "),
    ]
    for pat, rep in subs:
        desc = re.sub(pat, rep, desc)
    return desc


class Generator:
    def __init__(self) -> None:
        inv = json.loads(INV.read_text(encoding="utf-8"))
        self.version: str = inv["bot_api_version"]
        self.types: list[dict] = inv["types"]
        self.methods: list[dict] = inv["methods"]
        self.by_name = {t["name"]: t for t in self.types}
        self.structs = [t for t in self.types if t["kind"] == "struct"]
        self.unions = [t for t in self.types if t["kind"] == "union"]
        self.markers = [t for t in self.types if t["kind"] == "marker"]
        self.union_names = {t["name"] for t in self.unions}
        self.union_of = {t["name"]: t["subtypes"] for t in self.unions}
        self._promote_attach_strings()
        self.discriminators: dict[str, tuple[str, dict[str, str]]] = {}
        self._find_discriminators()
        self.emitted: list[Path] = []
        self.scc_of: dict[str, int] = {}
        self.order: list[str] = []
        self._analyze_graph()
        self.terminating: set[str] = set()
        self._compute_terminating()
        self.union_order: dict[str, list[str]] = {}
        self._compute_union_order()

    def _promote_attach_strings(self) -> None:
        """Fields documented as String but accepting attach:// upload
        references (nested media, thumbnails, covers, sticker payloads) become
        tgbot::InputFile so users can upload through them directly.  The
        passthrough forms serialize verbatim, so round-trips are unaffected."""
        count = 0
        for entry in self.structs + self.methods:
            for f in entry.get("fields", entry.get("params", [])):
                if f["type"] == {"kind": "string"} and "attach://" in f["description"]:
                    f["type"] = {"kind": "ref", "name": "InputFile"}
                    count += 1
        self.attach_promotions = count

    # ---------------------------------------------------------------- unions
    def literal_of_struct(self, sname: str) -> tuple[str, str] | None:
        """(discriminator field, literal) declared by a struct, if any.

        "must be one of ..." describes an enumeration, not a single constant,
        so it must not match (it would bake the literal "one" into fields
        like InputSticker.format)."""
        for f in self.by_name[sname].get("fields", []):
            if f["type_raw"] == "String" and f["required"]:
                m = re.search(r'always ["“]([A-Za-z0-9_]+)["”]', f["description"]) or re.search(
                    r"must be (?!one of\b)([a-z0-9_]+)", f["description"]
                )
                if m:
                    return (f["name"], m.group(1))
        return None

    def _find_discriminators(self) -> None:
        """For each discriminated union: (field, {subtype: literal})."""
        for u in self.unions:
            name = u["name"]
            if name in STRUCTURAL_UNIONS:
                continue
            self.discriminators[name] = self._discriminate(name, u["subtypes"])
        for members, alias in NAMED_ADHOC_UNIONS.items():
            self.discriminators[alias] = self._discriminate(alias, sorted(members))

    def _discriminate(self, name: str, subtypes: list[str]) -> tuple[str, dict[str, str]]:
        field_names = set()
        literals: dict[str, str] = {}
        for sub in subtypes:
            found = self.literal_of_struct(sub)
            if not found:
                raise SystemExit(f"union {name}: no discriminator literal in {sub}")
            field_names.add(found[0])
            literals[sub] = found[1]
        if len(field_names) != 1:
            raise SystemExit(f"union {name}: mixed discriminator fields {field_names}")
        return (next(iter(field_names)), literals)

    def _collision_key(self, union: str, candidates: list[str]) -> dict[str, str | None]:
        """For subtypes sharing a literal, a required field unique to each (the
        last candidate falls through to else and may be None)."""
        result: dict[str, str | None] = {}
        for sub in candidates:
            mine = [f["name"] for f in self.by_name[sub].get("fields", []) if f["required"]]
            others: set[str] = set()
            for o in candidates:
                if o != sub:
                    others |= {f["name"] for f in self.by_name[o].get("fields", [])}
            unique = [n for n in mine if n not in others]
            result[sub] = unique[0] if unique else None
        missing = [s for s, k in result.items() if k is None]
        if len(missing) > 1:
            raise SystemExit(f"union {union}: cannot disambiguate {missing}")
        return result

    # ----------------------------------------------------------- type graph
    def _value_deps(self, ast: dict, *, top: bool = True) -> set[str]:
        """Types whose *definition* must precede a field of this AST type.
        Array elements never require completeness (vector allows incomplete)."""
        kind = ast["kind"]
        if kind == "array":
            return set()
        if kind == "ref":
            name = ast["name"]
            if name == "InputFile":
                return set()
            if name in self.union_of:
                deps = set()
                for sub in self.union_of[name]:
                    deps.add(sub)
                return deps
            return {name}
        if kind == "union":
            opts = ast["options"]
            names = self._union_ref_names(opts)
            if names is None:
                return set()  # ChatId / InputFile-or-String: no struct deps
            deps: set[str] = set()
            for n in names:
                deps |= self._value_deps({"kind": "ref", "name": n})
            return deps
        return set()

    def _union_ref_names(self, opts: list[dict]) -> list[str] | None:
        if all(o["kind"] == "ref" for o in opts):
            names = [o["name"] for o in opts]
            if "InputFile" in names:
                return None
            return names
        return None

    def _analyze_graph(self) -> None:
        graph: dict[str, set[str]] = defaultdict(set)
        nodes = [t["name"] for t in self.structs] + [t["name"] for t in self.markers]
        node_set = set(nodes)
        for t in self.structs:
            for f in t.get("fields", []):
                for dep in self._value_deps(f["type"]):
                    if dep in node_set:
                        graph[t["name"]].add(dep)
        # Tarjan SCC (iterative).
        index: dict[str, int] = {}
        low: dict[str, int] = {}
        on_stack: set[str] = set()
        stack: list[str] = []
        counter = [0]
        scc_id = [0]

        def strongconnect(root: str) -> None:
            work = [(root, iter(sorted(graph[root])))]
            index[root] = low[root] = counter[0]
            counter[0] += 1
            stack.append(root)
            on_stack.add(root)
            while work:
                v, it = work[-1]
                advanced = False
                for w in it:
                    if w not in index:
                        index[w] = low[w] = counter[0]
                        counter[0] += 1
                        stack.append(w)
                        on_stack.add(w)
                        work.append((w, iter(sorted(graph[w]))))
                        advanced = True
                        break
                    if w in on_stack:
                        low[v] = min(low[v], index[w])
                if advanced:
                    continue
                work.pop()
                if low[v] == index[v]:
                    while True:
                        w = stack.pop()
                        on_stack.discard(w)
                        self.scc_of[w] = scc_id[0]
                        if w == v:
                            break
                    scc_id[0] += 1
                if work:
                    parent = work[-1][0]
                    low[parent] = min(low[parent], low[v])

        for n in nodes:
            if n not in index:
                strongconnect(n)

        # Topological order of the DAG that remains once boxed edges (same-SCC)
        # are dropped.  Kahn over reversed edges: deps first.
        dag: dict[str, set[str]] = {n: set() for n in nodes}
        for a, deps in graph.items():
            for b in deps:
                if self.scc_of[a] != self.scc_of[b]:
                    dag[a].add(b)
                elif a != b:
                    # A genuine same-SCC pair: both get boxed, no edge either way.
                    pass
        indeg = {n: 0 for n in nodes}
        rdeps: dict[str, set[str]] = defaultdict(set)
        for a, deps in dag.items():
            indeg[a] = len(deps)
            for b in deps:
                rdeps[b].add(a)
        ready = sorted(n for n, d in indeg.items() if d == 0)
        order: list[str] = []
        while ready:
            n = ready.pop(0)
            order.append(n)
            for a in sorted(rdeps[n]):
                indeg[a] -= 1
                if indeg[a] == 0:
                    ready.append(a)
            ready.sort()
        if len(order) != len(nodes):
            raise SystemExit("type graph is not a DAG after boxing")
        self.order = order

    def _eager_closure(self) -> dict[str, set[str]]:
        """Transitive closure of "default construction eagerly constructs".

        Required struct-value and Box fields construct their type; required
        union-value fields conservatively construct every subtype (the actual
        first alternative is what this analysis is choosing).  Vectors and
        optionals construct nothing.
        """
        eager: dict[str, set[str]] = defaultdict(set)
        for t in self.structs:
            for f in t.get("fields", []):
                if not f["required"]:
                    continue
                ast = f["type"]
                names: list[str] = []
                if ast["kind"] == "ref" and ast["name"] != "InputFile":
                    n = ast["name"]
                    names = self.union_of.get(n, [n])
                elif ast["kind"] == "union":
                    refs = self._union_ref_names(ast["options"])
                    if refs:
                        names = refs
                for n in names:
                    if n in self.by_name and self.by_name[n]["kind"] in ("struct", "marker"):
                        eager[t["name"]].add(n)
        closure: dict[str, set[str]] = {}

        def dfs(n: str) -> set[str]:
            if n in closure:
                return closure[n]
            closure[n] = set()  # cycle-tolerant: cycles resolve to partial sets
            acc: set[str] = set()
            for d in eager.get(n, ()):
                acc.add(d)
                acc |= dfs(d)
            closure[n] = acc
            return acc

        for t in self.structs:
            dfs(t["name"])
        return closure

    def _compute_union_order(self) -> None:
        """Variant alternative order: doc order, except the first alternative
        must be default-construction-safe (defaulting the variant must never
        re-enter the union through a required Box field, e.g. RichTextBold's
        required Box<RichText> text)."""
        closure = self._eager_closure()
        all_sets = {u["name"]: u["subtypes"] for u in self.unions}
        for members, alias in NAMED_ADHOC_UNIONS.items():
            all_sets[alias] = sorted(members)
        for name, subs in all_sets.items():
            member_set = set(subs)
            safe = [s for s in subs if not (closure.get(s, set()) & member_set)]
            if not safe:
                raise SystemExit(f"union {name}: no default-safe first alternative")
            first = safe[0]
            self.union_order[name] = [first] + [s for s in subs if s != first]

    def field_is_boxed(self, owner: str, ast: dict) -> bool:
        deps = self._value_deps(ast)
        return any(self.scc_of.get(d) == self.scc_of.get(owner) for d in deps if d != "")

    # ------------------------------------------------------------ C++ types
    def cpp_base_type(self, ast: dict, owner: str) -> str:
        kind = ast["kind"]
        if kind in SCALAR_CPP:
            return SCALAR_CPP[kind]
        if kind == "array":
            return f"std::vector<{self.cpp_base_type(ast['item'], owner)}>"
        if kind == "ref":
            return ast["name"]
        if kind == "union":
            opts = ast["options"]
            kinds = sorted(o["kind"] for o in opts)
            if kinds == ["integer", "string"]:
                return "ChatId"
            names = [o["name"] for o in opts if o["kind"] == "ref"]
            if "InputFile" in names:
                return "InputFile"  # "InputFile or String"
            if frozenset(names) == REPLY_MARKUP_SET:
                return "ReplyMarkup"
            # Inline subset of a named union: use the smallest named superset
            # (e.g. sendMediaGroup's media list fits both InputMedia and the
            # larger InputPollMedia; InputMedia is the right home).
            supersets = [u for u in self.unions if set(names) <= set(u["subtypes"])]
            if supersets:
                best = min(supersets, key=lambda u: (len(u["subtypes"]), u["name"]))
                return best["name"]
            if frozenset(names) in NAMED_ADHOC_UNIONS:
                return NAMED_ADHOC_UNIONS[frozenset(names)]
            raise SystemExit(f"{owner}: unmapped inline union {names}")
        raise SystemExit(f"{owner}: unknown AST kind {kind}")

    def cpp_field_type(self, owner: str, field: dict) -> str:
        base = self.cpp_base_type(field["type"], owner)
        if self.field_is_boxed(owner, field["type"]):
            base = f"Box<{base}>"
        if not field["required"]:
            base = f"std::optional<{base}>"
        return base

    # -------------------------------------------------------------- headers
    def emit_types_hpp(self) -> str:
        out: list[str] = []
        w = out.append
        w(BANNER)
        w("#pragma once\n\n")
        w("/// @file\n/// @brief Every Telegram Bot API object type "
          f"(Bot API {self.version}).\n\n")
        w("#include <cstdint>\n#include <optional>\n#include <string>\n"
          "#include <variant>\n#include <vector>\n\n")
        w("#include <nlohmann/json.hpp>\n\n")
        w('#include "tgbot/box.hpp"\n#include "tgbot/detail/json.hpp"\n'
          '#include "tgbot/input_file.hpp"\n\n')
        w("namespace tgbot {\n\n")

        # Forward declarations.
        w("// -- forward declarations "
          "---------------------------------------------------\n")
        for name in sorted(t["name"] for t in self.structs + self.markers):
            w(f"struct {name};\n")
        w("\n")

        # Aliases: ChatId, ReplyMarkup, and every documented union.
        w("// -- union aliases "
          "-----------------------------------------------------------\n\n")
        w("/// Chat identifier: a numeric id or a @c \\@channelusername string.\n")
        w("using ChatId = std::variant<std::int64_t, std::string>;\n\n")
        w("/// Any of the four keyboard-control markups accepted by send methods.\n")
        w("using ReplyMarkup = std::variant<InlineKeyboardMarkup, ReplyKeyboardMarkup,\n"
          "                                 ReplyKeyboardRemove, ForceReply>;\n\n")
        for u in self.unions:
            doc = wrap_comment(esc_doc(paraphrase(u["description"])), "")
            w(doc + "\n")
            w(f"/// @see https://core.telegram.org/bots/api#{u['anchor']}\n")
            alts = ", ".join(self.union_order[u["name"]])
            w(f"using {u['name']} = std::variant<{alts}>;\n\n")
        for members, alias in sorted(NAMED_ADHOC_UNIONS.items(), key=lambda kv: kv[1]):
            w(f"/// Media accepted where the reference lists an unnamed union of\n"
              f"/// input-media types.\n")
            alts = ", ".join(self.union_order[alias])
            w(f"using {alias} = std::variant<{alts}>;\n\n")

        w("}  // namespace tgbot\n\n")

        # adl_serializer declarations (variants live in namespace std, so ADL
        # cannot find free functions; full specializations are required).
        w("// -- serializer declarations for the variant aliases "
          "------------------------\n")
        w("namespace nlohmann {\n")
        alias_names = (["ChatId", "ReplyMarkup"] + [u["name"] for u in self.unions]
                       + sorted(NAMED_ADHOC_UNIONS.values()))
        seen_sig: set[str] = set()
        for name in alias_names:
            sig = self.alias_signature(name)
            if sig in seen_sig:
                raise SystemExit(f"duplicate variant signature for {name}")
            seen_sig.add(sig)
            w(f"template <>\nstruct adl_serializer<tgbot::{name}> {{\n")
            w(f"    static void to_json(json& j, const tgbot::{name}& value);\n")
            w(f"    static void from_json(const json& j, tgbot::{name}& value);\n")
            w("};\n")
        w("}  // namespace nlohmann\n\n")

        w("namespace tgbot {\n\n")
        w("// -- object types "
          "------------------------------------------------------------\n\n")
        marker_names = {t["name"] for t in self.markers}
        for name in self.order:
            t = self.by_name[name]
            doc = wrap_comment(esc_doc(paraphrase(t["description"])), "")
            w(doc + "\n")
            w(f"/// @see https://core.telegram.org/bots/api#{t['anchor']}\n")
            if name in marker_names:
                w(f"struct {name} {{}};\n\n")
            else:
                lit = self.literal_of_struct(name)
                w(f"struct {name} {{\n")
                for f in t.get("fields", []):
                    fdoc = wrap_comment(esc_doc(f["description"]), "    ")
                    w(fdoc + "\n")
                    cpp = self.cpp_field_type(name, f)
                    if lit and f["name"] == lit[0] and f["required"] and cpp == "std::string":
                        init = f' = "{lit[1]}"'  # discriminator pre-filled
                    elif f["type"]["kind"] == "true" and f["required"]:
                        init = "{true}"  # documented as always True
                    elif cpp in ("bool", "double", "std::int64_t"):
                        init = "{}"
                    else:
                        # No NSDMI here: object types may hold vectors of
                        # yet-incomplete elements (recursive rich content),
                        # and a {} initializer would instantiate their
                        # constructors mid-definition.
                        init = ""
                    w(f"    {cpp} {f['name']}{init};\n")
                w("};\n\n")
            w(f"/// Serializes {name} into its Bot API wire format.\n")
            w(f"void to_json(nlohmann::json& j, const {name}& value);\n")
            w(f"/// Parses {name} from its Bot API wire format.\n")
            w(f"void from_json(const nlohmann::json& j, {name}& value);\n\n")
        w("}  // namespace tgbot\n")
        return "".join(out)

    def alias_signature(self, name: str) -> str:
        if name == "ChatId":
            return "int64,string"
        if name == "ReplyMarkup":
            return ",".join(sorted(REPLY_MARKUP_SET))
        return ",".join(sorted(self.union_members(name)))

    def union_members(self, name: str) -> list[str]:
        if name in self.union_of:
            return self.union_of[name]
        for members, alias in NAMED_ADHOC_UNIONS.items():
            if alias == name:
                return sorted(members)
        raise KeyError(name)

    # ------------------------------------------------------------- json cpp
    def emit_struct_json(self, t: dict) -> str:
        name = t["name"]
        out: list[str] = []
        w = out.append
        fields = t.get("fields", [])
        if not fields:
            w(f"void to_json(nlohmann::json& j, const {name}& /*value*/) {{\n"
              "    j = nlohmann::json::object();\n}\n")
            w(f"void from_json(const nlohmann::json& /*j*/, {name}& /*value*/) {{}}\n\n")
            return "".join(out)
        w(f"void to_json(nlohmann::json& j, const {name}& value) {{\n")
        w("    j = nlohmann::json::object();\n")
        for f in fields:
            w(f'    detail::write(j, "{f["name"]}", value.{f["name"]});\n')
        w("}\n")
        w(f"void from_json(const nlohmann::json& j, {name}& value) {{\n")
        for f in fields:
            w(f'    detail::read(j, "{f["name"]}", value.{f["name"]});\n')
        w("}\n\n")
        return "".join(out)

    def emit_union_json(self, name: str) -> str:
        out: list[str] = []
        w = out.append
        qn = f"tgbot::{name}"
        w(f"void adl_serializer<{qn}>::to_json(json& j, const {qn}& value) {{\n")
        w("    std::visit([&j](const auto& alt) { j = alt; }, value);\n}\n")
        w(f"void adl_serializer<{qn}>::from_json(const json& j, {qn}& value) {{\n")
        if name == "ChatId":
            w("    if (j.is_string()) {\n        value = j.get<std::string>();\n")
            w("    } else {\n        value = j.get<std::int64_t>();\n    }\n}\n\n")
            return "".join(out)
        if name == "ReplyMarkup":
            pairs = [
                ("inline_keyboard", "InlineKeyboardMarkup"),
                ("keyboard", "ReplyKeyboardMarkup"),
                ("remove_keyboard", "ReplyKeyboardRemove"),
                ("force_reply", "ForceReply"),
            ]
            for i, (key, sub) in enumerate(pairs):
                kw = "if" if i == 0 else "} else if"
                w(f'    {kw} (j.contains("{key}")) {{\n        value = j.get<tgbot::{sub}>();\n')
            w('    } else {\n        throw tgbot::Error("unrecognized ReplyMarkup object");\n    }\n}\n\n')
            return "".join(out)
        if name == "MaybeInaccessibleMessage":
            w('    if (j.at("date").get<std::int64_t>() == 0) {\n')
            w("        value = j.get<tgbot::InaccessibleMessage>();\n")
            w("    } else {\n        value = j.get<tgbot::Message>();\n    }\n}\n\n")
            return "".join(out)
        if name == "InputMessageContent":
            for i, (sub, key) in enumerate(INPUT_MESSAGE_CONTENT_ORDER):
                kw = "if" if i == 0 else "} else if"
                w(f'    {kw} (j.contains("{key}")) {{\n        value = j.get<tgbot::{sub}>();\n')
            w('    } else {\n        throw tgbot::Error("unrecognized InputMessageContent object");\n    }\n}\n\n')
            return "".join(out)

        field, literals = self.discriminators[name]
        by_literal: dict[str, list[str]] = defaultdict(list)
        for sub in self.union_members(name):
            by_literal[literals[sub]].append(sub)
        w(f'    const auto& d = j.at("{field}").get_ref<const std::string&>();\n')
        first = True
        for literal in sorted(by_literal):
            subs = by_literal[literal]
            kw = "if" if first else "} else if"
            first = False
            w(f'    {kw} (d == "{literal}") {{\n')
            if len(subs) == 1:
                w(f"        value = j.get<tgbot::{subs[0]}>();\n")
            else:
                keys = self._collision_key(name, subs)
                ordered = [s for s in subs if keys[s] is not None]
                fallback = [s for s in subs if keys[s] is None]
                inner_first = True
                for s in ordered[: len(ordered) if fallback else -1]:
                    ikw = "if" if inner_first else "} else if"
                    inner_first = False
                    w(f'        {ikw} (j.contains("{keys[s]}")) {{\n')
                    w(f"            value = j.get<tgbot::{s}>();\n")
                last = fallback[0] if fallback else ordered[-1]
                w(f"        }} else {{\n            value = j.get<tgbot::{last}>();\n        }}\n")
        w("    } else {\n")
        w(f'        throw tgbot::Error("unknown {name} {field}: " + d);\n    }}\n}}\n\n')
        return "".join(out)

    def emit_json_shards(self) -> list[str]:
        # Weighted round-robin so shards compile in similar time.
        items: list[tuple[int, str, str]] = []
        for t in self.structs + self.markers:
            items.append((len(t.get("fields", [])) + 3, "struct", t["name"]))
        alias_names = (["ChatId", "ReplyMarkup"] + [u["name"] for u in self.unions]
                       + sorted(NAMED_ADHOC_UNIONS.values()))
        for a in alias_names:
            items.append((6, "union", a))
        shards: list[list[tuple[str, str]]] = [[] for _ in range(NUM_JSON_SHARDS)]
        weights = [0] * NUM_JSON_SHARDS
        for weight, kind, name in sorted(items, reverse=True):
            i = weights.index(min(weights))
            weights[i] += weight
            shards[i].append((kind, name))

        files: list[str] = []
        for shard in shards:
            out: list[str] = [BANNER]
            out.append('#include "tgbot/api_error.hpp"\n#include "tgbot/types.hpp"\n\n')
            struct_part = [n for k, n in shard if k == "struct"]
            union_part = [n for k, n in shard if k == "union"]
            if struct_part:
                out.append("namespace tgbot {\n\n")
                for n in sorted(struct_part):
                    out.append(self.emit_struct_json(self.by_name[n]))
                out.append("}  // namespace tgbot\n\n")
            if union_part:
                out.append("namespace nlohmann {\n\n")
                for n in sorted(union_part):
                    out.append(self.emit_union_json(n))
                out.append("}  // namespace nlohmann\n")
            files.append("".join(out))
        return files

    # ------------------------------------------------------------- registry
    def emit_registry(self) -> str:
        out: list[str] = [BANNER]
        w = out.append
        w('#include "tgbot/detail/registry.hpp"\n\n#include "tgbot/types.hpp"\n\n')
        w("namespace tgbot::detail {\n\n")
        w("namespace {\n\n")
        w("// Taking the address of each serializer proves the symbol exists;\n")
        w("// a registry entry cannot lie about its implementation.\n")
        w("template <typename T>\n")
        w("constexpr bool proves_type() {\n")
        w("    void (*to)(nlohmann::json&, const T&) = nullptr;\n")
        w("    void (*from)(const nlohmann::json&, T&) = nullptr;\n")
        w("    to = static_cast<void (*)(nlohmann::json&, const T&)>(&to_json);\n")
        w("    from = static_cast<void (*)(const nlohmann::json&, T&)>(&from_json);\n")
        w("    return to != nullptr && from != nullptr;\n}\n\n")
        w("template <typename T>\nconstexpr bool proves_alias() {\n")
        w("    using S = nlohmann::adl_serializer<T>;\n")
        w("    void (*to)(nlohmann::json&, const T&) = &S::to_json;\n")
        w("    void (*from)(const nlohmann::json&, T&) = &S::from_json;\n")
        w("    return to != nullptr && from != nullptr;\n}\n\n")
        w("}  // namespace\n\n")
        w("const std::vector<std::string_view>& implemented_types() {\n")
        w("    static const std::vector<std::string_view> names = [] {\n")
        w("        std::vector<std::string_view> v;\n")
        for t in self.structs + self.markers:
            w(f'        static_assert(proves_type<{t["name"]}>());\n')
            w(f'        v.emplace_back("{t["name"]}");\n')
        for u in self.unions:
            w(f'        static_assert(proves_alias<{u["name"]}>());\n')
            w(f'        v.emplace_back("{u["name"]}");\n')
        w('        v.emplace_back("InputFile");  // handwritten in input_file.cpp\n')
        w("        return v;\n    }();\n    return names;\n}\n\n")
        w("}  // namespace tgbot::detail\n")
        return "".join(out)

    # ------------------------------------------------------ round-trip data
    def _compute_terminating(self) -> None:
        """Fixpoint: a struct terminates when every *required* field can be
        sampled finitely (unions terminate when any subtype does; arrays
        always terminate because [] is valid)."""
        for t in self.markers:
            self.terminating.add(t["name"])
        self.terminating.add("InputFile")

        def ast_term(ast: dict) -> bool:
            kind = ast["kind"]
            if kind in SCALAR_CPP or kind == "array":
                return True
            if kind == "ref":
                n = ast["name"]
                if n in self.union_of:
                    return any(s in self.terminating for s in self.union_of[n])
                return n in self.terminating
            if kind == "union":
                names = self._union_ref_names(ast["options"])
                if names is None:
                    return True  # ChatId / InputFile-or-String
                return any(n in self.terminating for n in names)
            return True

        changed = True
        while changed:
            changed = False
            for t in self.structs:
                if t["name"] in self.terminating:
                    continue
                if all(ast_term(f["type"]) for f in t.get("fields", []) if f["required"]):
                    self.terminating.add(t["name"])
                    changed = True
        missing = [t["name"] for t in self.structs if t["name"] not in self.terminating]
        if missing:
            raise SystemExit(f"non-terminating required cycles: {missing}")

    def pick_subtype(self, names: list[str], stack: tuple[str, ...]) -> str:
        """First union subtype that can be sampled finitely, avoiding the
        current expansion stack when possible."""
        fresh = [n for n in names if n in self.terminating and n not in stack]
        if fresh:
            return fresh[0]
        terminating = [n for n in names if n in self.terminating]
        if terminating:
            return terminating[0]
        raise SystemExit(f"no terminating subtype among {names}")

    def sample(self, name: str, depth: int, stack: tuple[str, ...]):
        t = self.by_name[name]
        if t["kind"] == "special":  # InputFile
            return "file-ref"
        if t["kind"] == "marker":
            return {}
        if t["kind"] == "union":
            return self.sample(self.pick_subtype(t["subtypes"], stack), depth, stack)
        obj = {}
        disc = None
        for u, (field, literals) in self.discriminators.items():
            if name in literals:
                disc = (field, literals[name])
                break
        for f in t.get("fields", []):
            if not f["required"] and (depth >= 2 or self._recurses(f["type"], stack)):
                continue
            if (name, f["name"]) in SAMPLE_OVERRIDES:
                obj[f["name"]] = SAMPLE_OVERRIDES[(name, f["name"])]
                continue
            if disc and f["name"] == disc[0]:
                obj[f["name"]] = disc[1]
                continue
            obj[f["name"]] = self.sample_of_ast(f["type"], depth + 1, stack + (name,))
        return obj

    def _recurses(self, ast: dict, stack: tuple[str, ...]) -> bool:
        kind = ast["kind"]
        if kind == "ref":
            n = ast["name"]
            if n in stack:
                return True
            if n in self.union_of:
                return any(s in stack for s in self.union_of[n])
            return False
        if kind == "array":
            return self._recurses(ast["item"], stack)
        if kind == "union":
            return any(o["kind"] == "ref" and self._recurses(o, stack) for o in ast["options"])
        return False

    def sample_of_ast(self, ast: dict, depth: int, stack: tuple[str, ...]):
        kind = ast["kind"]
        if kind == "integer":
            return 7
        if kind == "string":
            return "s"
        if kind in ("boolean", "true"):
            return True
        if kind == "float":
            return 1.5
        if kind == "array":
            if self._recurses(ast["item"], stack) or depth > 6:
                return []
            return [self.sample_of_ast(ast["item"], depth + 1, stack)]
        if kind == "ref":
            name = ast["name"]
            if name in self.union_of:
                return self.sample(self.pick_subtype(self.union_of[name], stack), depth, stack)
            return self.sample(name, depth, stack)
        if kind == "union":
            kinds = sorted(o["kind"] for o in ast["options"])
            if kinds == ["integer", "string"]:
                return 7
            names = [o["name"] for o in ast["options"] if o["kind"] == "ref"]
            if "InputFile" in names:
                return "file-ref"
            return self.sample(self.pick_subtype(names, stack), depth, stack)
        raise SystemExit(f"sample: unknown kind {kind}")

    def emit_roundtrip_shards(self) -> list[str]:
        cases: list[tuple[str, str, object]] = []  # (label, cpp expr type, sample)
        for t in self.structs + self.markers:
            cases.append((t["name"], t["name"], self.sample(t["name"], 0, ())))
        for u in self.unions:
            for sub in u["subtypes"]:
                cases.append((f"{u['name']}/{sub}", u["name"], self.sample(sub, 0, ())))
        shards: list[list[tuple[str, str, object]]] = [[] for _ in range(NUM_TEST_SHARDS)]
        for i, c in enumerate(cases):
            shards[i % NUM_TEST_SHARDS].append(c)
        files = []
        for si, shard in enumerate(shards):
            out: list[str] = [BANNER]
            w = out.append
            w('#include "roundtrip.hpp"\n\n')
            w("// NOLINTBEGIN\n")
            w(f"const std::vector<tgbot::test::RoundtripCase>& tgbot::test::corpus_{si}() {{\n")
            w("    static const std::vector<RoundtripCase> cases = {\n")
            for label, cpp, sample in shard:
                sample_json = json.dumps(sample, separators=(",", ":")).replace("\\", "\\\\").replace('"', '\\"')
                w("        {\n")
                w(f'            "{label}",\n')
                w(f'            "{sample_json}",\n')
                w(f"            [](const nlohmann::json& j) {{ return nlohmann::json(j.get<tgbot::{cpp}>()); }},\n")
                w("        },\n")
            w("    };\n    return cases;\n}\n")
            w("// NOLINTEND\n")
            files.append("".join(out))
        return files

    # -------------------------------------------------------- method layer
    def _compute_file_bearing(self) -> set[str]:
        """Types that can transitively carry an InputFile upload."""

        def mentions(ast: dict, bearing: set[str]) -> bool:
            kind = ast["kind"]
            if kind == "ref":
                n = ast["name"]
                if n == "InputFile":
                    return True
                if n in self.union_of:
                    return any(s in bearing for s in self.union_of[n])
                return n in bearing
            if kind == "array":
                return mentions(ast["item"], bearing)
            if kind == "union":
                names = self._union_ref_names(ast["options"]) or []
                if any(o["kind"] == "ref" and o["name"] == "InputFile" for o in ast["options"]):
                    return True
                return any(mentions({"kind": "ref", "name": n}, bearing) for n in names)
            return False

        bearing: set[str] = set()
        changed = True
        while changed:
            changed = False
            for t in self.structs:
                if t["name"] in bearing:
                    continue
                if any(mentions(f["type"], bearing) for f in t.get("fields", [])):
                    bearing.add(t["name"])
                    changed = True
        return bearing

    @staticmethod
    def pascal(method: str) -> str:
        return method[0].upper() + method[1:]

    def params_struct_name(self, m: dict) -> str | None:
        return f"{self.pascal(m['name'])}Params" if m["params"] else None

    def return_cpp(self, ast: dict) -> str:
        kind = ast["kind"]
        if kind == "true":
            return "bool"
        if kind in SCALAR_CPP:
            return SCALAR_CPP[kind]
        if kind == "ref":
            return ast["name"]
        if kind == "array":
            return f"std::vector<{self.return_cpp(ast['item'])}>"
        if kind == "union":
            opts = {json.dumps(o, sort_keys=True) for o in ast["options"]}
            expected = {
                json.dumps({"kind": "ref", "name": "Message"}, sort_keys=True),
                json.dumps({"kind": "true"}, sort_keys=True),
            }
            if opts == expected:
                return "MessageOrBool"
            raise SystemExit(f"unhandled union return: {ast}")
        raise SystemExit(f"unhandled return kind: {kind}")

    def return_parse_expr(self, ast: dict) -> str:
        cpp = self.return_cpp(ast)
        if cpp == "MessageOrBool":
            return "detail::parse_message_or_bool(std::move(result))"
        return f"result.get<{cpp}>()"

    def method_doc(self, m: dict, indent: str = "") -> str:
        doc = wrap_comment(esc_doc(paraphrase(m["description"])), indent)
        doc += f"\n{indent}///\n"
        if m["params"]:
            doc += f"{indent}/// @param params see {self.params_struct_name(m)}.\n"
        doc += (f"{indent}/// @throws ApiError on a Bot API error, NetworkError when "
                f"transport fails.\n")
        doc += f"{indent}/// @see https://core.telegram.org/bots/api#{m['anchor']}\n"
        return doc

    def emit_api_hpp(self, file_bearing: set[str]) -> str:
        out: list[str] = []
        w = out.append
        w(BANNER)
        w("#pragma once\n\n")
        w(f"/// @file\n/// @brief tgbot::Api — every Bot API {self.version} method.\n\n")
        w("#include <chrono>\n#include <cstdint>\n#include <optional>\n"
          "#include <string>\n#include <utility>\n#include <variant>\n#include <vector>\n\n")
        w('#include "tgbot/api_client.hpp"\n#include "tgbot/detail/collect.hpp"\n'
          '#include "tgbot/types.hpp"\n\n')
        w("namespace tgbot {\n\n")
        w("/// Result of the editMessage* family: the edited Message for normal\n"
          "/// messages, or @c true when the target was an inline message.\n")
        w("using MessageOrBool = std::variant<Message, bool>;\n\n")
        w("namespace detail {\n\n")
        w("/// Parses a result that is either a Message object or literal true.\n")
        w("inline MessageOrBool parse_message_or_bool(nlohmann::json&& result) {\n")
        w("    if (result.is_boolean()) {\n        return result.get<bool>();\n    }\n")
        w("    return result.get<Message>();\n}\n\n")
        w("}  // namespace detail\n\n")

        # Params structs.
        for m in self.methods:
            if not m["params"]:
                continue
            sname = self.params_struct_name(m)
            w(f"/// Parameters of Api::{m['name']}(); fields mirror the official\n")
            w(f"/// documentation order, so designated initializers read like the docs.\n")
            w(f"/// @see https://core.telegram.org/bots/api#{m['anchor']}\n")
            w(f"struct {sname} {{\n")
            for p in m["params"]:
                pdoc = wrap_comment(esc_doc(p["description"]), "    ")
                w(pdoc + "\n")
                cpp = self.cpp_field_type(f"method {m['name']}", p)
                # NSDMI on every field: keeps designated initializers free of
                # -Wmissing-field-initializers under GCC/Clang -Wextra.
                w(f"    {cpp} {p['name']}{{}};\n")
            w("};\n\n")

        # The Api class.
        w("/// @brief Typed access to every Bot API method.\n///\n")
        w("/// Thin, thread-safe wrapper over tgbot::ApiClient: each method builds\n")
        w("/// the request (promoting it to multipart when params carry uploads),\n")
        w("/// applies the client's retry policy, and parses the typed result.\n")
        w("class Api {\npublic:\n")
        w("    /// Creates the Api for @p token.\n")
        w("    explicit Api(std::string token, ApiClient::Options options = {})\n")
        w("        : client_(std::move(token), std::move(options)) {}\n\n")
        w("    /// Wraps an existing client (custom transport, base URL, ...).\n")
        w("    explicit Api(ApiClient client) : client_(std::move(client)) {}\n\n")
        for m in self.methods:
            w(self.method_doc(m, "    "))
            ret = self.return_cpp(m["return"])
            sname = self.params_struct_name(m)
            if sname is None:
                w(f"    {ret} {m['name']}() const;\n\n")
            else:
                required = any(p["required"] for p in m["params"])
                dflt = "" if required else " = {}"
                w(f"    {ret} {m['name']}(const {sname}& params{dflt}) const;\n\n")
        w("    /// The underlying client (token, options, transport).\n")
        w("    const ApiClient& client() const noexcept { return client_; }\n\n")
        w("private:\n    ApiClient client_;\n};\n\n")
        w("}  // namespace tgbot\n")
        return "".join(out)

    def emit_collect_generated(self, file_bearing: set[str]) -> tuple[str, str]:
        hpp: list[str] = [BANNER]
        hpp.append("#pragma once\n\n")
        hpp.append("/// @file\n/// @brief Generated collect_files overloads for "
                   "InputFile-bearing types.\n\n")
        hpp.append('#include <vector>\n\n#include "tgbot/detail/collect.hpp"\n'
                   '#include "tgbot/types.hpp"\n\nnamespace tgbot {\n\n')
        cpp: list[str] = [BANNER]
        cpp.append('#include "tgbot/detail/collect_generated.hpp"\n\n'
                   "namespace tgbot {\n\n")
        for t in self.structs:
            if t["name"] not in file_bearing:
                continue
            hpp.append(f"void collect_files(const {t['name']}& value, "
                       "std::vector<MultipartPart>& out);\n")
            cpp.append(f"void collect_files(const {t['name']}& value, "
                       "std::vector<MultipartPart>& out) {\n")
            for f in t.get("fields", []):
                if self._ast_carries_file(f["type"], file_bearing):
                    cpp.append(f"    collect_files(value.{f['name']}, out);\n")
            cpp.append("}\n\n")
        hpp.append("\n}  // namespace tgbot::detail\n")
        cpp.append("}  // namespace tgbot::detail\n")
        return "".join(hpp), "".join(cpp)

    def _ast_carries_file(self, ast: dict, file_bearing: set[str]) -> bool:
        kind = ast["kind"]
        if kind == "ref":
            n = ast["name"]
            if n == "InputFile":
                return True
            if n in self.union_of:
                return any(s in file_bearing for s in self.union_of[n])
            return n in file_bearing
        if kind == "array":
            return self._ast_carries_file(ast["item"], file_bearing)
        if kind == "union":
            if any(o["kind"] == "ref" and o["name"] == "InputFile" for o in ast["options"]):
                return True
            names = self._union_ref_names(ast["options"]) or []
            return any(self._ast_carries_file({"kind": "ref", "name": n}, file_bearing)
                       for n in names)
        return False

    def emit_api_shards(self, file_bearing: set[str], count: int = 4) -> list[str]:
        shards: list[list[dict]] = [[] for _ in range(count)]
        weights = [0] * count
        for m in sorted(self.methods, key=lambda m: -len(m["params"])):
            i = weights.index(min(weights))
            weights[i] += len(m["params"]) + 3
            shards[i].append(m)
        files = []
        for shard in shards:
            out: list[str] = [BANNER]
            w = out.append
            w('#include "tgbot/api.hpp"\n'
              '#include "tgbot/detail/collect_generated.hpp"\n\n')
            w("namespace tgbot {\n\n")
            for m in sorted(shard, key=lambda m: m["name"]):
                ret = self.return_cpp(m["return"])
                sname = self.params_struct_name(m)
                if sname is None:
                    w(f"{ret} Api::{m['name']}() const {{\n")
                    w(f'    auto result = client_.call("{m["name"]}", '
                      "nlohmann::json::object());\n")
                else:
                    w(f"{ret} Api::{m['name']}(const {sname}& params) const {{\n")
                    w("    nlohmann::json body = nlohmann::json::object();\n")
                    for p in m["params"]:
                        w(f'    detail::write(body, "{p["name"]}", params.{p["name"]});\n')
                    file_params = [p for p in m["params"]
                                   if self._ast_carries_file(p["type"], file_bearing)]
                    if file_params:
                        w("    std::vector<MultipartPart> files;\n")
                        for p in file_params:
                            w(f"    collect_files(params.{p['name']}, files);\n")
                    files_arg = "std::move(files)" if file_params else "{}"
                    if m["name"] == "getUpdates":
                        # Long polling: transport timeout must exceed the poll.
                        w("    std::chrono::milliseconds timeout{};\n")
                        w("    if (params.timeout.has_value()) {\n")
                        w("        timeout = std::chrono::seconds(*params.timeout + 10);\n")
                        w("    }\n")
                        w(f'    auto result = client_.call("{m["name"]}", std::move(body), '
                          f"{files_arg}, timeout);\n")
                    else:
                        w(f'    auto result = client_.call("{m["name"]}", std::move(body), '
                          f"{files_arg});\n")
                w(f"    return {self.return_parse_expr(m['return'])};\n}}\n\n")
            w("}  // namespace tgbot\n")
            files.append("".join(out))
        return files

    def emit_method_registry(self) -> str:
        out: list[str] = [BANNER]
        w = out.append
        w('#include "tgbot/detail/registry.hpp"\n\n#include "tgbot/api.hpp"\n\n')
        w("namespace tgbot::detail {\n\nnamespace {\n\n")
        w("template <typename M>\nconstexpr bool proves_method(M m) {\n"
          "    return m != nullptr;\n}\n\n}  // namespace\n\n")
        w("const std::vector<std::string_view>& implemented_methods() {\n")
        w("    static const std::vector<std::string_view> names = [] {\n")
        w("        std::vector<std::string_view> v;\n")
        for m in self.methods:
            w(f"        static_assert(proves_method(&Api::{m['name']}));\n")
            w(f'        v.emplace_back("{m["name"]}");\n')
        w("        return v;\n    }();\n    return names;\n}\n\n")
        w("}  // namespace tgbot::detail\n")
        return "".join(out)

    def emit_method_smoke(self) -> str:
        out: list[str] = [BANNER]
        w = out.append
        w('#include "method_smoke.hpp"\n\n')
        w("// NOLINTBEGIN\n")
        w("const std::vector<tgbot::test::MethodSmokeCase>& tgbot::test::method_corpus() {\n")
        w("    static const std::vector<MethodSmokeCase> cases = {\n")
        for m in self.methods:
            result = self.return_sample(m["return"])
            esc = json.dumps(result, separators=(",", ":")).replace("\\", "\\\\").replace('"', '\\"')
            call = f"api.{m['name']}({{}})" if m["params"] else f"api.{m['name']}()"
            w("        {\n")
            w(f'            "{m["name"]}",\n')
            w(f'            "{esc}",\n')
            w(f"            [](const tgbot::Api& api) {{ (void){call}; }},\n")
            w("        },\n")
        w("    };\n    return cases;\n}\n")
        w("// NOLINTEND\n")
        return "".join(out)

    def return_sample(self, ast: dict):
        kind = ast["kind"]
        if kind == "true":
            return True
        if kind == "integer":
            return 7
        if kind == "string":
            return "s"
        if kind == "boolean":
            return True
        if kind == "float":
            return 1.5
        if kind == "array":
            return [self.return_sample(ast["item"])]
        if kind == "ref":
            # Minimal object: required fields only (depth >= 2 prunes optionals).
            return self.sample(ast["name"], 2, ())
        if kind == "union":
            return True  # MessageOrBool: exercise the boolean arm here
        raise SystemExit(f"return sample: unknown kind {kind}")

    # ---------------------------------------------------------------- write
    def write(self, path: Path, content: str) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
        self.emitted.append(path)
        print(f"  wrote {path.relative_to(ROOT)}")

    @staticmethod
    def format_emitted(paths: list[Path]) -> None:
        """Best effort: keep generated sources clang-format-clean so the
        format gate and the regeneration-is-clean gate agree."""
        import shutil
        import subprocess

        exe = shutil.which("clang-format")
        if exe is None:
            print("  (clang-format not found; skipping format of generated files)")
            return
        cpp = [str(p) for p in paths if p.suffix in (".hpp", ".cpp")]
        subprocess.run([exe, "-i", *cpp], check=True)
        print(f"  clang-formatted {len(cpp)} generated files")

    def run(self) -> None:
        # Structural-union dispatch tables must cover the unions exactly; a
        # version bump that extends them has to fail generation, not runtime.
        imc = {name for name, _key in INPUT_MESSAGE_CONTENT_ORDER}
        if imc != set(self.union_of["InputMessageContent"]):
            raise SystemExit(
                "InputMessageContent dispatch table out of date: "
                f"{sorted(imc ^ set(self.union_of['InputMessageContent']))}"
            )
        if set(self.union_of["MaybeInaccessibleMessage"]) != {"Message", "InaccessibleMessage"}:
            raise SystemExit("MaybeInaccessibleMessage shape changed; update generator")

        boxed = [
            (t["name"], f["name"])
            for t in self.structs
            for f in t.get("fields", [])
            if self.field_is_boxed(t["name"], f["type"])
        ]
        print(f"Bot API {self.version}: {len(self.structs)} structs, "
              f"{len(self.unions)} unions, {len(self.markers)} markers; "
              f"{len(boxed)} boxed fields")
        for owner, field in boxed:
            print(f"    boxed: {owner}.{field}")
        self.write(ROOT / "include/tgbot/types.hpp", self.emit_types_hpp())
        for i, content in enumerate(self.emit_json_shards()):
            self.write(ROOT / f"src/generated/types_json_{i}.cpp", content)
        self.write(ROOT / "src/generated/registry.cpp", self.emit_registry())
        for i, content in enumerate(self.emit_roundtrip_shards()):
            self.write(ROOT / f"tests/unit/generated/roundtrip_corpus_{i}.cpp", content)

        file_bearing = self._compute_file_bearing()
        print(f"  file-bearing types: {len(file_bearing)}")
        self.write(ROOT / "include/tgbot/api.hpp", self.emit_api_hpp(file_bearing))
        collect_hpp, collect_cpp = self.emit_collect_generated(file_bearing)
        self.write(ROOT / "include/tgbot/detail/collect_generated.hpp", collect_hpp)
        self.write(ROOT / "src/generated/collect_files.cpp", collect_cpp)
        for i, content in enumerate(self.emit_api_shards(file_bearing)):
            self.write(ROOT / f"src/generated/api_methods_{i}.cpp", content)
        self.write(ROOT / "src/generated/method_registry.cpp", self.emit_method_registry())
        self.write(ROOT / "tests/unit/generated/method_smoke_corpus.cpp",
                   self.emit_method_smoke())
        self.write(
            ROOT / "include/tgbot/version.hpp",
            BANNER
            + "#pragma once\n\n#include <string_view>\n\nnamespace tgbot {\n\n"
              "/// The Telegram Bot API version this library implements.\n"
              "/// @see https://core.telegram.org/bots/api-changelog\n"
              f'constexpr std::string_view api_version() noexcept {{ return "{self.version}"; }}\n\n'
              "/// The version of the tgbot library itself.\n"
              'constexpr std::string_view library_version() noexcept { return "0.1.0"; }\n\n'
              "}  // namespace tgbot\n",
        )
        self.format_emitted(self.emitted)


if __name__ == "__main__":
    Generator().run()
